import type { Metadata } from "next";
import { Anek_Odia } from "next/font/google";
import "@/assets/styles/globals.scss";

const AnekOdia = Anek_Odia({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={AnekOdia.className}>{children}</body>
    </html>
  );
}
